### PR TITLE
New features

### PR DESCRIPTION
**Pull request by ensonic**
Add more mappings. Convert more commands.

### CODE REVIEW

**Comment by sofar** [comment]
The minetest-lapis mod you point to is hopelessly broken and doesn't even have the right textures in github. If we add new mods, they should really be well-maintained and actually work.

**Comment by sofar** [comment]
The other 3 patches are fine. If you take out the lapis patch I'll merge this PR.

**Comment by ensonic** [comment]
I took the original lapis mod and uploaded a copy to my github account. This has the missing textures. The first patch has been adjusted to load the mod from the new location. It would be nice to have it in the minetestmods project, but I can't send a PR to create a new repo.

**Comment by sofar** [comment]
https://github.com/ensonic/minetest-lapis is missing, 404.

I'm very cautious about adding new mods, note that in my README I explicitly also state why I never added Lapis and I still am opposed to making cosmetic non-functional conversions.

Before adding lapis I really want to assure that the mod actually is properly OSS myself and the textures aren't copyrighted either.

**Comment by sofar** [comment]
Seems you just put the wrong url in lua. I wonder if @LNJ2 wants to maintain it in minetest-mods and take your patch? I'd be up for moving lapis to minetest-mods.

**Comment by LNJ2** [comment]
Here is the newest version: https://github.com/LNJ2/lapis
I just updated the README and added it to my real github-account.
This mod was my first one, and as I wrote it I didn't even know how to use git (from the command line and not with the web-interface).

I already thought about moving it to minetest-mods.

**Comment by sofar** [comment]
@ensonic can you change it to minetest-mods/lapis and check it still works? Then I'll merge.

**Comment by ensonic** [comment]
Thanks, updated and tested!

**Pull request merged**
