### PR TITLE
Fixed vines, chests, and doors.

### PR DESCRIPTION
**Pull request by MysticTempest**
I fixed vines, and chests so they're oriented correctly, and not excessively placed.

I also went ahead, and fixed the door issue reported by "AccidentallyRhine", here: https://forum.minetest.net/viewtopic.php?f=12&t=13709&start=75#p301057

I did this by forking the original 'doors' mod from Minetest Game, and updating the 'get-mods' script. While I was doing that, I also added support for converting the other wooden doors in Minecraft to the basic wooden door. 
So, the simplicity that this tool aims for is kept, while also providing some additional support for the new doors.

### CODE REVIEW

**Comment by sofar** [comment]
Can you split off the `doors` part? I am not happy about the replacement door code, the goal is really to stay close to mtg doors, and convert to those. This worked in the past, and undoing it in this way isn't in line with the project goals.

**Comment by MysticTempest** [comment]
Alrighty, I removed the door updates, and left in the vines & chests fixes. 

That'll leave the doors broken again. Maybe y'all can fix the doors on the MTG side, as it broke when meshes replaced the top/bottom nodes. And, the conversion code in the current 'doors' mod can't handle these since they don't have any code to register the old style doors in the first place.

**Comment by sofar** [comment]
Yeah, the idea is to let the door conversion code work for us. I didn't realize it was broken at all, but we should be able to do a replacement that doesn't require a whole forked door mod. If anything, we can put an LBM in place instead.

**Comment by sofar** [comment]
Actually, I remember now. The LBM could work for us, but it doesn't run because the lbm won't run right after mapgen. If, after conversion and opening the map ONCE, you delete the `lbm_introduction_times` from env_meta.txt, the door conversion code works OK.

The way to fix this would be to either let the LBM automatically work for us, or to convert to the new door nodes directly in mcimport, and not drag in old door mod code.

**Pull request merged**
